package io.github.roccobot.aiv

import android.content.ContentProvider
import android.content.ContentValues
import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import android.net.Uri
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.runBlocking
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config
import org.robolectric.shadows.ShadowContentResolver
import java.io.File

@RunWith(AndroidJUnit4::class)
@Config(shadows = [ArchivioAperto::class])
class IgnoredPsdTest {
    private val app = ApplicationProvider.getApplicationContext<android.content.Context>()

    @Before fun prepare() {
        ShadowContentResolver.registerProviderInternal("media", PsdMediaProvider())
    }

    @Test fun `folder counts and cover ignore PSD rows classified as images`() = runBlocking {
        val bucket = Folder.buckets(app).single()
        assertEquals(3, bucket.pictures)
        assertEquals(1, bucket.clips)
        assertEquals("8", bucket.cover?.lastPathSegment)
        val facts = Folder.weigh(app, 10)
        assertEquals(4, facts.shots + facts.clips)
        assertEquals(40L, facts.bytes)
    }

    @Test fun `search grid and thumbnail generation share the PSD exclusion`() = runBlocking {
        val expected = listOf("8", "7", "6", "1")
        assertEquals(expected, Folder.everything(app, emptySet()).map { it.lastPathSegment })
        val search = Folder.byName(app, "sample", emptySet()) as Folder.Lookup.Found
        assertEquals(listOf("8", "6", "1"), search.series.items.map { it.lastPathSegment })
        val grid = Folder.newestIn(app, 10) as Folder.Lookup.Found
        assertEquals(expected, grid.series.items.map { it.lastPathSegment })
    }

    @Test fun `system folders omit PSD while retaining ordinary documents`() = runBlocking {
        val dir = File(app.filesDir, "psd-system").apply { mkdirs() }
        try {
            File(dir, "sample.PSD").writeText("PSD")
            File(dir, "sample.txt").writeText("document")
            File(dir, "sample.png").writeText("PNG")
            assertEquals(listOf("sample.png", "sample.txt"), Tree.list(dir).map { it.file.name })
        } finally { dir.deleteRecursively() }
    }
}

// Runs the actual selection generated by Folder in SQLite, including NULL values.
class PsdMediaProvider : ContentProvider() {
    private val database: SQLiteDatabase by lazy {
        val database = SQLiteDatabase.create(null)
        database.execSQL("CREATE TABLE media (_id INTEGER, bucket_id INTEGER, _display_name TEXT, _size INTEGER, _data TEXT, bucket_display_name TEXT, media_type INTEGER, mime_type TEXT, date_modified INTEGER)")
        val rows = listOf(
            Triple("sample.jpg", "/sdcard/Images/sample.jpg", "image/jpeg"),
            Triple("sample.psd", "/sdcard/Images/sample.psd", "image/jpeg"),
            Triple("sample.PSD", "/sdcard/Images/sample.PSD", "image/jpeg"),
            Triple("sample.jpg", "/sdcard/Images/disguised.jpg", "IMAGE/VND.ADOBE.PHOTOSHOP"),
            Triple(null, "/sdcard/Images/unnamed.PsD", null),
            Triple("sample.mp4", "/sdcard/Images/sample.mp4", "video/mp4"),
            Triple(null, null, null),
            Triple("sample.psd.png", "/sdcard/Images/sample.psd.png", "image/png")
        )
        rows.forEachIndexed { index, row ->
            database.execSQL("INSERT INTO media VALUES (?, 10, ?, 10, ?, 'Images', ?, ?, ?)",
                arrayOf<Any?>(index + 1, row.first, row.second, if (index == 5) 3 else 1, row.third, index + 1))
        }
        database
    }
    override fun onCreate() = true
    override fun query(uri: Uri, projection: Array<out String>?, selection: String?,
        selectionArgs: Array<out String>?, sortOrder: String?): Cursor =
        database.query("media", projection, selection, selectionArgs, null, null, sortOrder)
    override fun getType(uri: Uri) = "image/jpeg"
    override fun insert(uri: Uri, values: ContentValues?): Uri? = null
    override fun update(uri: Uri, values: ContentValues?, selection: String?, selectionArgs: Array<out String>?) = 0
    override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?) = 0
}
